# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokick < Formula
  desc ""
  homepage "https://github.com/hackit-nashville/gokick"
  version "0.1.0"
  license "Mozilla Public License Version 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.0/gokick_0.1.0_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "58180d5c88c03760cb1e640b34d90a973a0bc69a41f71bb7241a524fc90426c2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.0/gokick_0.1.0_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8ad9fb518e90939f43af8beb8fe30dc1dff86a331bd179007cb53f1136f20181"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.0/gokick_0.1.0_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3f3a2140092fa8c9e199e637a63de7817aaf7809148a2ae60f819ba4de1adf26"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.0/gokick_0.1.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "31294592fb47e351f2aa48279f2cb17061d2073bd053687bda0137ce2c613941"
    end
  end

  def install
    bin.install "gokick"
  end
end
