# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GetSsmParams < Formula
  desc ""
  homepage "https://github.com/justmiles/go-get-ssm-params"
  version "1.8.0"
  license "Mozilla Public License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/justmiles/go-get-ssm-params/releases/download/v1.8.0/get-ssm-params_1.8.0_Darwin_arm64.tar.gz"
      sha256 "bdbcff4f260b9a71eb27830f1279a224fb0436c9b99656d19432b796fe828003"

      def install
        bin.install "get-ssm-params"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/justmiles/go-get-ssm-params/releases/download/v1.8.0/get-ssm-params_1.8.0_Darwin_x86_64.tar.gz"
      sha256 "7ab992ea0fdb2a15658e5d927db60a42c164b5eb674e21d63261089d4bdb00d6"

      def install
        bin.install "get-ssm-params"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/justmiles/go-get-ssm-params/releases/download/v1.8.0/get-ssm-params_1.8.0_Linux_x86_64.tar.gz"
      sha256 "ae2caba52f600c2539823e0c94350f3e66aed3df7db7bb0877c6affb9c9f0330"

      def install
        bin.install "get-ssm-params"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justmiles/go-get-ssm-params/releases/download/v1.8.0/get-ssm-params_1.8.0_Linux_arm64.tar.gz"
      sha256 "a22d81b06b462c79485e5927bcf1c3e4f48813187397c92201a93621c3b47938"

      def install
        bin.install "get-ssm-params"
      end
    end
  end
end
