# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokick < Formula
  desc ""
  homepage "https://github.com/hackit-nashville/gokick"
  version "0.1.1"
  license "Mozilla Public License Version 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.1/gokick_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "f81ccc7695d68388cfbf166b926d54ad73ee458267a8ebb867601e545ff9d9ee"
    end
    if Hardware::CPU.arm?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.1/gokick_0.1.1_Darwin_arm64.tar.gz"
      sha256 "e7899cf12d23165c722743e4f599bd226e605e02bb7e2ecd7894c1f45d645bd4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.1/gokick_0.1.1_Linux_x86_64.tar.gz"
      sha256 "7a68e7f60c57176195bee1dd9f98ade8ab00ed315cce514853aa238689e815de"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hackit-nashville/gokick/releases/download/v0.1.1/gokick_0.1.1_Linux_arm64.tar.gz"
      sha256 "0f3a3203714a4acb470aea04b4caaab1d37c25541a12c47d5341aa1df53f877a"
    end
  end

  def install
    bin.install "gokick"
  end
end
