# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrNotifier < Formula
  desc ""
  homepage "https://github.com/chrispruitt/pr-notifier"
  version "0.1.0"
  license "Mozilla Public License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chrispruitt/pr-notifier/releases/download/v0.1.0/pr-notifier_0.1.0_Darwin_arm64.tar.gz"
      sha256 "5f7cd2572852931bcbee263e5c6c0c356c6720fff48af05ade055c728d4ac10f"

      def install
        bin.install "pr-notifier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chrispruitt/pr-notifier/releases/download/v0.1.0/pr-notifier_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "5048a6804cad83074f25be3299b5d86d237bef7a90e4f82a320ececcfeb105ad"

      def install
        bin.install "pr-notifier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrispruitt/pr-notifier/releases/download/v0.1.0/pr-notifier_0.1.0_Linux_arm64.tar.gz"
      sha256 "b323e505b39eaf532d412fe050b9da89e8c835329a3a7a9eab103200ead66c20"

      def install
        bin.install "pr-notifier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chrispruitt/pr-notifier/releases/download/v0.1.0/pr-notifier_0.1.0_Linux_x86_64.tar.gz"
      sha256 "e60c43f318d1a56e7461911a58e56925302abeac4317082ec50bf331fe9ba638"

      def install
        bin.install "pr-notifier"
      end
    end
  end
end
