# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SsmParameterStore < Formula
  desc ""
  homepage "https://github.com/justmiles/ssm-parameter-store"
  version "0.0.7"
  license "Mozilla Public License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/justmiles/ssm-parameter-store/releases/download/v0.0.7/ssm-parameter-store_0.0.7_Darwin_arm64.tar.gz"
      sha256 "31b913b9ae73009c8399abcf543575aac1ca5eb732ea6e7fe826480a19f27678"

      def install
        bin.install "ssm-parameter-store"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/justmiles/ssm-parameter-store/releases/download/v0.0.7/ssm-parameter-store_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "5793f2f37bf6fe4943925072254a6ff889c8b7942460472ccf66fbefbc1d3e4b"

      def install
        bin.install "ssm-parameter-store"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justmiles/ssm-parameter-store/releases/download/v0.0.7/ssm-parameter-store_0.0.7_Linux_arm64.tar.gz"
      sha256 "ce1993aef22b8b6bc0823dc6ea4e7846583646f933fcc8ebbf41ae2e0b5702a9"

      def install
        bin.install "ssm-parameter-store"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/justmiles/ssm-parameter-store/releases/download/v0.0.7/ssm-parameter-store_0.0.7_Linux_x86_64.tar.gz"
      sha256 "096ca5a186da91772e86bfaa286af4acd6522b6b777a13b760a687a7ee4ffc7e"

      def install
        bin.install "ssm-parameter-store"
      end
    end
  end
end
